name: mobile_app
description: "AI Resume Builder & CV Mobile Application"
publish_to: 'none'
version: 1.0.0+18

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Data & Local Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  json_annotation: ^4.9.0


  # Backend & AI
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  cloud_functions: ^5.1.0
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.2.1

  # Monetization
  google_mobile_ads: ^5.1.0

  # UI & Utils
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  pdf: ^3.10.8
  printing: ^5.13.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_card_swiper: ^7.2.0
  file_picker: ^8.0.0
  read_pdf_text: ^0.3.1
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  html_unescape: ^2.0.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F9FAFB"
  color_dark: "#111827"
  image: "assets/icon/app_icon.png"
  android_12:
    image: "assets/icon/app_icon.png"
    color: "#F9FAFB"
    color_dark: "#111827"
